name: Daily Encouragement Email

on:
  schedule:
    - cron: '35 23 * * *'  # ריצה כל יום ב-23:35 UTC (01:35 בלילה שעון ישראל בחורף)
  workflow_dispatch:       # אפשרות להרצה ידנית


jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai

      - name: Run daily email script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python daily_encouragement.py
